task:
    alias: pkg
    freebsd_instance:
      cpu: 4
      memory: 16G
      matrix:
        - image: freebsd-13-1-release-amd64
        # image: freebsd-14-0-current-amd64-v20220701

    env:
      CIRRUS_CLONE_DEPTH: 1
      GITHUB_TOKEN: ENCRYPTED[0ba3b24834d4b97a22e13d65dd9ef0de718c7129a9b7305fa0ddaa26af432f426156f8cf1f1575665a58192828b7ab24]
      BATCH: 1
      CCACHE_DIR: "/tmp/.ccache"
      CCACHE_COMPRESS: 1
      CCACHE_SIZE: "200M"
      CCACHE_STATIC_PREFIX: "/usr/local"
      CCACHE_NOSTATS: 1
      CCACHE_TEMPDIR: "/tmp"
      WITH_CCACHE_BUILD: "YES"
      PORTS_BRANCH: "2023Q1"
    portstree_cache:
      folder: /usr/ports/
    ccache_cache:
      folder: ${CCACHE_DIR}
    pkg_cache:
      folder: /var/cache/pkg/
    timeout_in: 90m

    prerequisites_script:
      - ASSUME_ALWAYS_YES=yes pkg bootstrap -f
      - pkg install -y git-lite

    portstree_setup_script:
      - if [ ! -f "/usr/ports/${PORTS_BRANCH}" ] ; then mkdir -p /usr/ports && fetch "https://github.com/freebsd/freebsd-ports/archive/refs/heads/${PORTS_BRANCH}.tar.gz" -o - | tar xf - -C /usr/ports --strip-components=1 && touch "/usr/ports/${PORTS_BRANCH}" ; fi

    ccache_setup_script:
      - env IGNORE_OSVERSION=yes pkg install -y ccache-static
      - ccache --max-size=${CCACHE_SIZE}
      - echo "WITH_CCACHE_BUILD=yes" >> /etc/make.conf

    build_script:
      - ./build.sh
      
    binary_artifacts:
      path: "FreeBSD:**/*"
